SQLALCHEMY_DATABASE_URI='sqlite://'
SQLALCHEMY_TRACK_MODIFICATIONS=False
MAIL_SERVER='smtp.gmail.com'
MAIL_PORT=465
MAIL_USE_TLS=False
MAIL_USE_SSL=True
MAIL_USERNAME='username'
MAIL_PASSWORD='password'
